name: pointAdvection
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - fiona
  - gdal
  - h5py
  - lxml
  - matplotlib
  - netCDF4
  - notebook
  - numpy
  - pyproj
  - python-dateutil
  - scipy>=1.10.1
  - shapely
  - timescale
  - pip
  - pip:
     - git+https://github.com/smithb/pointCollection.git
