name: pointAdvection
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - gdal
  - h5py
  - matplotlib
  - netCDF4
  - notebook
  - numpy
  - pyproj
  - python-dateutil
  - scipy
  - pip
  - pip:
     - git+https://github.com/tsutterley/pyTMD.git
     - git+https://github.com/smithb/pointCollection.git
